export const UPDATE_ROOMNAME = 'UPDATE_ROOMNAME';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const UPDATE_LINK = 'UPDATE_LINK';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const TOGGLE_BGCOLOR = 'TOGGLE_BGCOLOR';
export const TOGGLE_PRIVATE = 'TOGGLE_PRIVATE';
export const CLICKED_CARD = 'CLICKED_CARD';